# Generated by Django 5.2.4 on 2025-07-28 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Місто')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_travel', models.DateField(verbose_name='Дата поїздки')),
                ('count_passenger', models.PositiveIntegerField(verbose_name='Кількість пасажирів')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='mainApp.city', verbose_name='З міста')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='mainApp.city', verbose_name='У місто')),
            ],
        ),
    ]
