# Generated by Django 5.2.4 on 2025-08-07 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Місто')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_trip', models.PositiveIntegerField(verbose_name='Номер рейсу')),
                ('bus_description', models.CharField(default='Без опису', max_length=255, verbose_name='Опис автобуса')),
                ('count_passengers', models.PositiveIntegerField(default=10, verbose_name='Кількість місць')),
                ('free_count_passengers', models.PositiveIntegerField(default=10, verbose_name='Вільні місця')),
                ('has_air_conditioning', models.BooleanField(default=False, verbose_name='Кондиціонер')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='Wi-Fi')),
                ('has_paid_socket', models.BooleanField(default=False, verbose_name='Розетка (платно)')),
                ('has_free_socket', models.BooleanField(default=False, verbose_name='Розетка (безкоштовно)')),
                ('has_seat_belts', models.BooleanField(default=False, verbose_name='Ремені безпеки')),
                ('has_wc', models.BooleanField(default=False, verbose_name='WC')),
                ('has_eticket', models.BooleanField(default=False, verbose_name='Без роздруковування')),
            ],
        ),
        migrations.CreateModel(
            name='TripRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Станція')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='mainApp.city', verbose_name='Місто')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_datetime', models.DateTimeField(verbose_name='Дата та час відправлення')),
                ('arrival_datetime', models.DateTimeField(verbose_name='Дата та час прибуття')),
                ('price_travel', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна поїздки')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_departures', to='mainApp.city', verbose_name='З міста')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_arrivals', to='mainApp.city', verbose_name='У місто')),
                ('from_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='mainApp.station', verbose_name='Зупинка відправлення')),
                ('to_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='mainApp.station', verbose_name='Зупинка прибуття')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_travel', models.DateField(verbose_name='Дата поїздки')),
                ('count_passenger', models.PositiveIntegerField(verbose_name='Кількість пасажирів')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_departures', to='mainApp.city', verbose_name='З міста')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_arrivals', to='mainApp.city', verbose_name='У місто')),
            ],
        ),
    ]
