# Generated by Django 5.2.4 on 2025-08-07 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='carrier',
            field=models.ForeignKey(limit_choices_to={'isCarrier': True}, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL, verbose_name='Перевізник'),
        ),
        migrations.AddField(
            model_name='triproute',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.route'),
        ),
        migrations.AddField(
            model_name='triproute',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_routes', to='mainApp.trip'),
        ),
        migrations.AlterUniqueTogether(
            name='station',
            unique_together={('city', 'name')},
        ),
    ]
