# Generated by Django 5.2.4 on 2025-08-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Станція'),
        ),
    ]
