# Generated by Django 5.2.4 on 2025-08-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_trip_bus_description_trip_carrier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='free_count_passengers',
            field=models.PositiveIntegerField(default=10, verbose_name='Вільні місця'),
        ),
    ]
