# Generated by Django 5.2.4 on 2025-08-08 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_station_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ByeTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.route', verbose_name='Маршрут')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought_tickets', to='mainApp.trip', verbose_name='Рейс')),
                ('user', models.ForeignKey(limit_choices_to={'isCarrier': False}, on_delete=django.db.models.deletion.CASCADE, related_name='bought_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Пасажир')),
            ],
        ),
    ]
