# Generated by Django 5.2.4 on 2025-08-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_trip_free_count_passengers'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='from_place',
            field=models.CharField(default='Неизвестно', max_length=250, verbose_name='Місце відправлення'),
        ),
        migrations.AddField(
            model_name='route',
            name='to_place',
            field=models.CharField(default='Неизвестно', max_length=250, verbose_name='Місце прибуття'),
        ),
    ]
