# Generated by Django 5.2.4 on 2025-08-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_byetickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='byetickets',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Кількість місць'),
        ),
    ]
