# Generated by Django 5.2.4 on 2025-08-08 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_byetickets_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='byetickets',
            old_name='order',
            new_name='count_passenger',
        ),
    ]
