# Generated by Django 5.2.4 on 2025-08-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_route_from_place_route_to_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='has_air_conditioning',
            field=models.BooleanField(default=False, verbose_name='Кондиціонер'),
        ),
        migrations.AddField(
            model_name='trip',
            name='has_free_socket',
            field=models.BooleanField(default=False, verbose_name='Розетка (безкоштовно)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='has_paid_socket',
            field=models.BooleanField(default=False, verbose_name='Розетка (платно)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='has_seat_belts',
            field=models.BooleanField(default=False, verbose_name='Ремені безпеки'),
        ),
        migrations.AddField(
            model_name='trip',
            name='has_wc',
            field=models.BooleanField(default=False, verbose_name='WC'),
        ),
        migrations.AddField(
            model_name='trip',
            name='has_wifi',
            field=models.BooleanField(default=False, verbose_name='Wi-Fi'),
        ),
    ]
