# Generated by Django 5.2.4 on 2025-08-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_trip_has_air_conditioning_trip_has_free_socket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='has_eticket',
            field=models.BooleanField(default=False, verbose_name='Без роздруковування'),
        ),
    ]
